### ISSUE TITLE
How to send a message with Document?

### ISSUE THREAD

**Issue by E-CommerceGO** [mirakl/sdk-php-shop#12]
Hello.

I am sending messages via the following API:

```
$request = new CreateOrderMessageRequest($order_number, array(
	'subject'            => 'new Subject',
	'body'               => 'Message',
	'to_customer'        => true,
	'to_operator'        => false,
  ));
```

How can I attach a document? I can't find the way.

Thank you!

**Comment by jreinke** [comment]
Hello,

To send a message, you must use API `OR43` or `M12`.
You have an example to add a document in the following file for example:
`src/Mirakl/MMP/Common/Request/Order/Message/CreateOrderThreadRequest.php`

Best.
