### ISSUE TITLE
Error creating products

### ISSUE THREAD

**Issue by E-CommerceGO** [mirakl/sdk-php-shop#14]
Hello!

I am creating products by API. When creating a product in the textile category, it asks me for the colorMP field as mandatory. Also this field is from a list of values.

I assign "Black" but it throws me the following error:

2006|The attribute 'colorMP' (colorMP) is not in the possible values set in the value list

The color is on the list which is the strange thing, is it possible that it is because it is a csv? if I do it by hand using Excel if it works.
Has it happened to someone and know how to solve it?

I attach the CSV file in the ZIP

Thank you!

[EGO1612950374.zip](https://github.com/mirakl/sdk-php-shop/files/5957233/EGO1612950374.zip)

**Comment by jreinke** [comment]
Hello @E-CommerceGO,

Since this is probably not related to the connector's code, can you contact us directly at the following email address please: support-magento-seller@mirakl.com
And can you specify the marketplace URL and your seller's name in the email please?

Thank you.
