### ISSUE TITLE
setHierarchyCode not work to filter the categories.

### ISSUE THREAD

**Issue by st-pimentel** [mirakl/sdk-php-shop#17]
Using the SDK to filter the categories seems the filter is not working.
Investigating the code I found that the attribute `hierarchy ` was mistaken by `hierarchy_code`.
In Postman the `hierarchy_code` not work to filter the category, but `hierarchy` do.

https://github.com/mirakl/sdk-php-shop/blob/39dd7ccceb373819cfbceb00c6bf5af6a7db1a62/src/Mirakl/MCI/Common/Request/Hierarchy/AbstractGetHierarchiesRequest.php#L23

In my local installation I tested putting the attribute and the filter works now.

My change:

```php
...
public $queryParams = ['hierarchy_code', 'hierarchy', 'max_level'];
...
```
Usage: 
```php
...
$request->setHierarchy("N-10001");
...
```

**Comment by jreinke** [comment]
Hello,

The v1.13.3 fixes the bug.
Thanks for your feedback.
