### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function GuzzleHttp\Psr7\build_query()

### ISSUE THREAD

**Issue by mainIine** [mirakl/sdk-php-shop#20]
The build_query() function no longer exists in Guzzle v7. The new function is **Query::build**

The row 169 in _src/Mirakl/Core/Client/AbstractApiClient.php_
```php
$options['query'] = GuzzleHttp\Psr7\build_query(array_merge($this->formatQueryParams($simpleParams), $duplicatedParams));
```

must be replaced with this one.
```php
$options['query'] = GuzzleHttp\Psr7\Query::build(array_merge($this->formatQueryParams($simpleParams), $duplicatedParams));
```

**Comment by jreinke** [comment]
Hello,

Thanks for your feedback, we are going to release a fix.

**Comment by jreinke** [comment]
The v1.13.5 has been released and should fix the bug.

Thank you.
