### ISSUE TITLE
GetHierarchiesRequest (H11) has wrong param hierarchy_code instead of hierarchy

### ISSUE THREAD

**Issue by ygascard** [mirakl/sdk-php-shop#22]
WIth latest version of the SDK GetHierarchiesRequest() uses parameter to set hierarchy category parent hierarchy_code instead of hierarchy as documented on the API doc for H11 request.

**Comment by amarie75** [comment]
Hi,

We have release a fix to add the `setHierarchy()` method.
The old method `setHierarchyCode()` still working.

Best regards,
Alexandre
