### ISSUE TITLE
OR28 - Request refunds on order lines. How to exclude from shipment?

### ISSUE THREAD

**Issue by TriJoe** [mirakl/sdk-php-shop#24]
[Mirakl documentation](https://debenhamsuk-prod.mirakl.net/help/api-doc/seller/mmp.html#OR28) shows you can use boolean **excluded_from_shipment** which removes the line item from the shipment. 

How can I set this option?

**Comment by jreinke** [comment]
Hello,

You should be able to add this parameter with the following code:
```
$refund->setData('excluded_from_shipment', true);
```
We will add it in the PHPDoc of the PHP SDK in future versions.

Best,
Johann
