### ISSUE TITLE
OR04 missing or no documentation

### ISSUE THREAD

**Issue by eclyptox** [mirakl/sdk-php-shop#26]
Hello. I am trying to use OR04, that it is mentioned in CHANGELOG from version v1.13.0 - 2021-01-22 

But in code I do not see anyhing.  

Thanks in advance

**Comment by jreinke** [comment]
Hello,

Actually, the API OR04 has been added since v1.14.0 for the sellers while it was available since v1.13.0 for the other roles.
That's why you could not find it in earlier versions. I have added the v1.14.0 to the current repository so you can use it.

Thanks for your feedback.

Best,
Johann
