### ISSUE TITLE
UpdateOffersRequest does not work

### ISSUE THREAD

**Issue by nsoft-dev** [mirakl/sdk-php-shop#34]
Hello,

when im using the UpdateOffersRequest, the quantity is not set in the shop, price too.
The result is always with the import_id, so i think the json-data is correct.

is there any solution?

This is my current code:
`
$url = "{$this->baseurl}/offers";
        $header = array(
            "Authorization: {$this->apikey}",
            "Content-Type: application/json"
        );
        $data = array(
            "update_delete" => "update",
            "state_code" => $Offer->state_code,
            "shop_sku" => $Offer->shop_sku,
            "quantity" => strval($Stock),
            "price" => $Offer->price,
            "product_id_type" => "EAN",
            "product_sku" => $Offer->product_sku
        );
        $data = array(
            'offers' => array(
                $data
            )
        );
$api = new ShopApiClient($this->baseurl, $this->apikey);
$request = new UpdateOffersRequest($data);
        $result = $api->updateOffers($request);
`

**Comment by jreinke** [comment]
Hello,

I think you have forgotten a level in your data array.
Please try this code instead:
```
$request = new UpdateOffersRequest(array($data));
```

**Comment by nsoft-dev** [comment]
No this doesnt work.
Result is Bad Request.

Here is the Code.
I think, this is ok, because i get the response with "import_id".
![phpstorm64_wGOrWVh8ej](https://user-images.githubusercontent.com/114478403/192541279-130f7961-8d1c-4419-8c9a-17b973f071f3.png)

**Comment by nsoft-dev** [comment]
Ok i have try this and i get this message with the OF02 Endpoint.
![UlrLCnlr8D](https://user-images.githubusercontent.com/114478403/192552650-d8daa871-2721-4b3b-90cb-9294c8510da2.png)

**Comment by nsoft-dev** [comment]
Oh really, when i do the requests again, i get this result.
![wyWtowbb8T](https://user-images.githubusercontent.com/114478403/192745673-dbabcee6-d2e9-4fe7-acde-320c86174187.png)

**Comment by nsoft-dev** [comment]
It works :)

Thanky you @jreinke
I forgott the EAN Number to enter as product_id.

**Comment by jreinke** [comment]
Great!
Thanks for your feedback.
