### ISSUE TITLE
Issue with products title

### ISSUE THREAD

**Issue by dalosa1414** [mirakl/sdk-php-shop#35]
Hi,
I'm using the sdk to import marketplace products but I'm getting title n/a,
I tried to put all the locale available but all of them gives me the same title.
There is any way of getting the correct title or description of the product in the correct locale? Or there is other attributes that can help me?

Very Thanks.

**Comment by jreinke** [comment]
Hello,

Can you share the code you are using and that generates the product title you mentioned please?

Thank you.
