### ISSUE TITLE
SOR28 - Request refund on order

### ISSUE THREAD

**Issue by Bouhnosaure** [mirakl/sdk-php-shop#39]
Hi, 

Is there a way to use the SOR28 method in order to request a refund on an order ? 

We are almost done on the implementation of the SDK and as we talked to a commercial team on mirakl (adeo) side, we need this feature to complete our implementation.

We can make our implementation but if it's in the SDK it will be more maintainable.

Thanks and have a nice day !

**Comment by jreinke** [comment]
Hello,

The API `SOR28` is not present in the SDK since it is related to Mirakl for Services.
Do you really want to use API `SOR28` or are you talking about API `OR28` that is realted to Mirakl Core?

Best regards.

**Comment by Bouhnosaure** [comment]
Hi, 

Thanks for your answer, it's not that i really want but the API documentation specifies that this method (SOR28) can refund a order entirely.

In order to use the OR28 we need to store order item identifiers to use this method.

It's not an issue, but it could save some space and requests for refunding a whole order.

Thanks, 

Alex
