### ISSUE TITLE
Field product_id_type, what are the optional values?

### ISSUE THREAD

**Issue by lanrenbulan** [mirakl/sdk-php-shop#41]
Hi,

I am using the API about offer, field product_ id_type, what are the optional values of type? I download offer to my own system, but I don't know how to generate a link to directly access the sales page.

**Comment by jreinke** [comment]
Hello,

This is the type associated to the value you have specified in the `product_id` field.
For example:
```
"product_id": "9400016774345"
"product_id_type": "EAN"
```

I hope it helps.

**Comment by jreinke** [comment]
Please access to the Help Center directly from your Mirakl environment under the Help tab.
