### ISSUE TITLE
Solution to manage Reviews ?

### ISSUE THREAD

**Issue by MaximeSEM** [mirakl/sdk-php-shop#47]
Hi,
We would like to manage our review's answers from our solution. It seems to miss two methods to do it: 
- One to get all evaluations updated from a date
- Another one to answer to an evaluation

Can we do that with the Mirakl api ?
Maybe in the future ?

**Comment by MaximeSEM** [comment]
Thanks for your feedback. I saw it and i use it, but it's a lot of call (need to browse all recent orders) to get the information.
I hope we will have a method in the future to request reviews ;)
Have a nice day

**Comment by jreinke** [comment]
Thanks for your feedback too, I will forward it to the right team.
Have a nice day! :)
