### ISSUE TITLE
How to get Mirakl SHOP_KEY (API Key) and HOSTNAME (Env url)

### ISSUE THREAD

**Issue by mukeshpiplai** [mirakl/sdk-php-shop#48]
I have MMP Seller account and also able to get Miraklconnect API client id and client secret but don't know How to get MMP API SHOP_KEY and HOSTNAME (Environment URL), Can anyone help.

**Comment by mhnkhalifa** [comment]
Hello,
Please reach out directly to the marketplace you are selling on, they will be able to help you with this request.
Thanks for your understaning.
