### ISSUE TITLE
Error in Products Import

### ISSUE THREAD

**Issue by inovecomm** [mirakl/sdk-php-shop#5]
I am trying to import products with P41, but i am having the same error in transformed file: 1001 | Category unknow.

I got the categories with H11 and use one of them in my import file.

So what am i doing wrong?

**Comment by olivervs** [comment]
Hello, I have a problem upating Stock of a producto I really dont know how to do it, can you bring me an example?

Thanky you!

**Comment by jreinke** [comment]
Hello @olivervs ,

You have some videos and documentation available that may help you updating the stock.
You can access it from your Mirakl back office under the "Help" tab.

**Comment by E-CommerceGO** [comment]
Hello!
I have a similar problem.
The error I get is: "1000 | The attribute 'shopReference' (Seller Reference (SKU)) is required"
As a header I use the value "shopReference".
Can I import a product directly without doing a mapping first? Using the default settings?

Thanks a lot!

**Comment by jreinke** [comment]
Hello @E-CommerceGO,

The mapping is mandatory to map your custom fields with the operator ones.

Johann
