### ISSUE TITLE
OR74 - Problems with order_documents

### ISSUE THREAD

**Issue by silvialort** [mirakl/sdk-php-shop#52]
Hello, we're trying to upload some customer's invoices to an order with documentation provided in resource OR74.  When we try to curl, we receive the error: 

**400 - Bad Request: problem with form param \'order_documents\'**

This is the data we send to Mirakl:

`array (
  'files' => 
  CURLFile::__set_state(array(
     'name' => '/path/to/invoice.pdf',
     'mime' => 'application/pdf',
     'postname' => 'orderid.pdf',
  )),
  'order_documents' => '{"file_name":"orderid.pdf","type_code":"CUSTOMER_INVOICE"}',
)`

Is there something we aren't taking into account when sending order_documents?

Thank you very much

**Comment by jreinke** [comment]
Hello,

I think the problem is that the `order_documents` field must be an array of object.
It should be something like that instead:
```
'order_documents' => '[{"file_name":"orderid.pdf","type_code":"CUSTOMER_INVOICE"}]'
```

**Comment by silvialort** [comment]
Hello, we tried that way and we couldn't make it work. 
However, we passed the order_documents info with xml format and it worked.
