### ISSUE TITLE
Miss a "s" in field'sname mapping

### ISSUE THREAD

**Issue by MaximeSEM** [mirakl/sdk-php-shop#53]
Hi,
I found a little mistake : 
https://github.com/mirakl/sdk-php-shop/blame/8b4b3a07917fd9bd5d436e00ef559aa88343624d/src/Mirakl/MCI/Common/Domain/Product/ProductImportResult.php#L48
`        'transform_lines_in_succes'       => 'transformed_lines_in_success',`
instead of 
`        'transform_lines_in_success'       => 'transformed_lines_in_success',`

**Comment by jreinke** [comment]
Hello,

Thanks for your feedback, it will be fixed in the next version.
