### ISSUE TITLE
How to create a product / product offer

### ISSUE THREAD

**Issue by MundoBoss** [mirakl/sdk-php-shop#57]
Hey !
Can't find a way to create a product !
I am able to create an offer of a product that already exist with updateoffer but its impossible to find a way to CREATE a product.

Anyone can help me ?

**Comment by Keed9** [comment]
Hello.

I can't help you, but, i have to ask, how you create an offer?, i want to update an offer, im testing the endpoint with postman, it returns 200 ok but the offer doesnt update, im kinda lose.
