### ISSUE TITLE
in the package an folder is miising : Mirakl\MMP\FrontOperator/

### ISSUE THREAD

**Issue by amarknit** [mirakl/sdk-php-shop#60]
Hello
When i am using this package then i find an error
Class 'Mirakl\MMP\FrontOperator\Domain\Offer' not found.
Can u send me the missing folder?
Thanks

**Comment by mhnkhalifa** [comment]
Hello @amarknit,
Please try updating your PHP SDK to the latest version. Version 1.19.3 was released and should fix this issue.
Thanks for your feedback.
