### ISSUE TITLE
OR13 Bad Request

### ISSUE THREAD

**Issue by egalindoEH** [mirakl/sdk-php-shop#63]
Hi, Im having a lot of issues with OR13 endpoint.
```php
$request = new ExportOrdersAsyncSubmitRequest();
$request->setStartUpdateDate(new \DateTime('2023-01-01T00:00'));
$request->setEndUpdateDate(new \DateTime('2024-03-19T00:00')); //Actually Im trying to use current day but is the same issue
$result = $api->exportOrdersAsync($request);
```

But after this gave me an exception: `400 Bad Request` response

Sometimes works but most common isn't. I tried changing timezone but is the same.

Im using:
PHP: ("php": "^8.0")
Mirakl: "mirakl/sdk-php-shop": "^1.20"

**Comment by egalindoEH** [comment]
Debugging sdk, I saw that sometimes async is false and others is true.

Why is happening this? 

Async equals false
![image](https://github.com/mirakl/sdk-php-shop/assets/108294256/2e1e40d0-70cd-4d7f-b782-05a4118a4c75)

Async equals true
![image](https://github.com/mirakl/sdk-php-shop/assets/108294256/6d18c816-7978-491a-ab5a-7c6224de17fd)

**Comment by amarie75** [comment]
Hello,

You have an exception: `400 Bad Request` response because the interval between the start date and the end date can't be greater than a year.
This information is mentioned in the response body
```
try {
    $result = $client->exportOrdersAsync($request);
} catch (\GuzzleHttp\Exception\ClientException $e) {
    throw new \Exception($e->getResponse()->getBody()->getContents());
}
```

Best regards,
Alexandre
