### ISSUE TITLE
problem whit setup

### ISSUE THREAD

**Issue by Alessandro8823** [mirakl/sdk-php-shop#73]
Hi i have create a folder in my root  api_mirakl/  and i have insert api key.

but if going to webpage i recive this error   

`Fatal error: Uncaught Error: Class "Mirakl\MMP\Shop\Client\ShopApiClient" not found in /home/hitechonline/public_html/api_mirakl/index.php:14 Stack trace: #0 {main} thrown in /home/hitechonline/public_html/api_mirakl/index.php on line 14`

**Comment by jreinke** [comment]
Hello,

It is probably because you did not include the autoloader correctly.
Can you share with us how you installed the Mirakl SDK and how you include the autoloader please?

Thank you.
