### ISSUE TITLE
add min_quantity_alert for OF52?

### ISSUE THREAD

**Issue by lanrenbulan** [mirakl/sdk-php-shop#74]
Return without the min_quantity_alert field in OF52.

**Comment by JPGrandclementMirakl** [comment]
Hello,

Thank you for reaching us.
Could you let me know where you found this field in OF52 response?
This field is present in OF22 and included in our SDK
https://github.com/mirakl/sdk-php-shop/blob/fda80ff1b6acaf443e9e559b052bb643b9607839/src/Mirakl/MMP/Common/Domain/Offer/AbstractOffer.php#L53

Does this answer your concern?
Regards,
JP

**Comment by lanrenbulan** [comment]
I'm sorry, I thought you were also API developers and that you could directly add this field in response to this API. I misunderstood
